openapi: 3.0.0

info:
  version: 1.1.1
  title: Wictiunary API

tags:
- name: Auth
  description: Auth API

paths:
  # [POST] Register
  /auth/register:
    post:
      tags:
      - Auth
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthData'
      responses:
        201:
          description: 'User is created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
  # [POST] Login
  /auth/login:
    post:
      tags:
      - Auth
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthData'
      responses:
        200:
          description: 'User is logged in'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
  # [POST] Logout
  /auth/logout:
    post:
      tags:
      - Auth
      operationId: logout
      responses:
        200:
          description: 'User is logged out'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
  # [GET] Me
  /auth/me:
    get:
      tags:
      - Auth
      operationId: me
      responses:
        200:
          description: 'User data is found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'

# definitions
components:
  schemas:
    AuthData:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: User's email
        password:
          type: string
          description: User's password
    UserData:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
              - _id
              - email
              - password
          properties:
            _id:
              type: string
              description: User's ID
            email:
              type: string
              description: User's Email
            password:
              type: string
              description: User's Password
        message:
          type: string
